# CI script
image: java:8-jdk

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle-cache"
  JAVA_OPTS: "-Xms1g -Xmx1g"

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle-cache

build:
  stage: build
  script: ./gradlew clean build jar
  artifacts:
    paths:
      - ./build/libs/*.jar
  only:
    - master
