# GitLab CI script
image: java:8-jdk

stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: ".gradle-cache"
  JAVA_OPTS: "-Xms1g -Xmx1g"

build:
  stage: build
  cache:
    paths:
      - .gradle-cache
  before_script:
    - export WINEPREFIX="`pwd`/.wine"
    - export WINDEBUG=-all
    - export WINEARCH=win32
  script:
    - chmod +x ./gradlew
    - ./gradlew clean build jar --info
  artifacts:
    paths:
      - ./build/libs/*.jar
  only:
    - master
